"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Account = { id: string; username: string; displayName: string; bio: string; avatar: string | null; email: string; createdAt: string };
export function ProfileSettings({ account }: { account: Account }) {
  const router = useRouter(); const [values, setValues] = useState({ username: account.username, displayName: account.displayName, bio: account.bio, avatar: account.avatar ?? "" }); const [passwords, setPasswords] = useState({ currentPassword: "", nextPassword: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); setMessage(""); setError(""); const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json() as { error?: string }; if (!response.ok) setError(data.error ?? "Unable to save changes."); else { setMessage("Profile updated."); router.refresh(); } setSaving(false); }
  async function logout() { const response = await fetch("/api/auth/logout", { method: "POST" }); const data = await response.json() as { redirectTo?: string }; router.replace(data.redirectTo ?? "/login?role=customer"); router.refresh(); }
  async function changePassword() { setError(""); setMessage(""); const response = await fetch("/api/profile/password", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(passwords) }); const data = await response.json() as { error?: string }; if (!response.ok) setError(data.error ?? "Unable to change password."); else { setMessage("Password changed."); setPasswords({ currentPassword: "", nextPassword: "" }); } }
  return <div className="settings-card"><div className="settings-avatar">{values.avatar ? <img src={values.avatar} alt="Profile preview" /> : values.displayName.slice(0, 2).toUpperCase()}</div><div className="settings-form"><label>Profile image URL<input value={values.avatar} onChange={(event) => setValues({ ...values, avatar: event.target.value })} placeholder="https://..." /></label><label>Display name<input value={values.displayName} onChange={(event) => setValues({ ...values, displayName: event.target.value })} /></label><label>Username<div className="input-prefix"><span>@</span><input value={values.username} onChange={(event) => setValues({ ...values, username: event.target.value.replace(/^@/, "") })} /></div></label><label>Bio<textarea maxLength={160} value={values.bio} onChange={(event) => setValues({ ...values, bio: event.target.value })} placeholder="A little about your food life" /></label>{error && <div className="form-message error">{error}</div>}{message && <div className="form-message success">{message}</div>}<div className="settings-actions"><button className="primary-button" onClick={save} disabled={saving}>{saving ? "Saving..." : "Save changes"}</button><button className="logout-button" onClick={logout}>Log out</button></div><div className="password-section"><h3>Change password</h3><label>Current password<input type="password" value={passwords.currentPassword} onChange={(event) => setPasswords({ ...passwords, currentPassword: event.target.value })} /></label><label>New password<input type="password" value={passwords.nextPassword} onChange={(event) => setPasswords({ ...passwords, nextPassword: event.target.value })} placeholder="8+ characters, upper, lower, number" /></label><button className="outline-button" onClick={changePassword}>Update password</button></div><p className="settings-note">Notifications, privacy, account deletion, and data export are reserved for the next account-security pass.</p></div></div>;
}
